### ISSUE TITLE
Issue with phhalHw_FieldReset command

### ISSUE THREAD

**Issue by oscole** [JohnMcLear/NXP-Raspberry-Pi-Card-Polling-Demo#2]
Thank you for your post John,
 I ran the sample code, however, the status return code at the line below indicates PH_ERR_INTERFACE_ERROR  Communication error.
Could you give some guidance on this as to ways I could troubleshoot further to determine what the cause of the error may be or any hints as to what could be causing this. 
When this line of code is run, it actually stops at the line and does not move to execute the codes below, but rather, restarts in the main loop.
Any guidance on this would be appreciated, as I have gone through tons of documentation without any success.

Line 325: Error here, status code 0x20B:
  /* Reset the RF field */
    PH_CHECK_SUCCESS_FCT(status, phhalHw_FieldReset(halReader));

**Comment by JohnMcLear** [comment]
I'm not working on this but I'm w/ main dev on the 20th so I will ask him to sort his code so it actually works and doesn't require my abstraction

**Comment by JohnMcLear** [comment]
Also fwiw I'm more inclined to help people that have contributed to other O/S projects, your profile is sparse to say the least

**Comment by oscole** [comment]
Thanks for your reply John, I dabbled a bit in the code and it started working after I initialized Logging, need to investigate further why this is the case though. My profile is a bit sparse as I have just started using Git, but thank you for the contributions that you have made, really am impressed with the work you have done with the NFC ring as well.

**Comment by JohnMcLear** [comment]
http://www.nxp.com/board/PNEV512R.html#documentation
